//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProawarenessMeetupDemos.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActiveSession
    {
        public System.Guid SessionID { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> ConnectedAt { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
